#' Install agents and skills as an AGENTS.md file for OpenAI Codex CLI
#'
#' Concatenates the requested content into a single `AGENTS.md` and writes it
#' to the location Codex CLI reads from. Codex CLI loads
#' `$CODEX_HOME/AGENTS.md` (default `~/.codex/AGENTS.md`) globally, and
#' `AGENTS.md` files walked from the git root toward the current working
#' directory.
#'
#' Codex has a default limit of ~32 KiB for combined AGENTS.md content
#' (`project_doc_max_bytes`); a warning is issued if the written file exceeds
#' that size.
#'
#' For `scope = "user"` (which writes under your home directory) the function
#' asks for confirmation in interactive sessions before writing. Non-interactive
#' callers proceed without prompting; set `options(nlmixr2llm.consent = TRUE)` to
#' pre-approve.
#'
#' @note On case-insensitive filesystems (macOS, Windows) the project-scope
#'   `AGENTS.md` and Positron's `agents.md` (see
#'   [install_positron()] with `style = "agents_md"`) are the **same file**, so
#'   installing both into one project means the second call overwrites the
#'   first. With default arguments the instruction content is identical, so this
#'   is harmless; if you pass different `packages`/`include` to each, only the
#'   last call's selection survives.
#'
#' @param scope `"user"` writes to `~/.codex/AGENTS.md`; `"project"` writes to
#'   `<path>/AGENTS.md`. The user-scope base is `$CODEX_HOME` if set, otherwise
#'   the home directory returned by `getOption("nlmixr2llm.home")` (defaulting to
#'   `~`); set `options(nlmixr2llm.home = tempdir())` to redirect user-scope
#'   writes away from the real home (used by the package's tests).
#' @param packages Character vector of nlmixr2-universe packages to include.
#'   Defaults to all available packages.
#' @param path Project root when `scope = "project"`. Defaults to the current
#'   working directory.
#' @param mode How to handle an existing file:
#'   * `"write"` (default) -- overwrite if present
#'   * `"append"` -- append a clearly delimited section to the existing file
#'   * `"error"` -- fail if the file exists
#' @param include Which content to include: `"both"` (default), `"agents"`,
#'   or `"skills"`.
#' @return Invisibly, the path written.
#' @export
#' @examples
#' \dontrun{
#' install_codex(scope = "project", packages = c("rxode2", "nlmixr2"))
#' install_codex(scope = "user", mode = "append")
#' }
install_codex <- function(scope = c("user", "project"),
                          packages = NULL,
                          path = ".",
                          mode = c("write", "append", "error"),
                          include = c("both", "agents", "skills")) {
  scope <- match.arg(scope)
  mode <- match.arg(mode)
  include <- match.arg(include)

  dst <- codex_path(scope, path)
  if (scope == "user" && !confirm_home_write(dirname(dst))) {
    message("Aborted: no file written.")
    return(invisible(character()))
  }
  dir.create(dirname(dst), recursive = TRUE, showWarnings = FALSE)

  pkgs <- intersect(packages %||% list_packages(), list_packages())
  body <- system_prompt(packages = pkgs, include = include)
  body <- paste0(
    "<!-- BEGIN nlmixr2llm -->\n",
    stamp_comment(pkgs, include), "\n",
    "<!-- Generated by the nlmixr2llm R package. ",
    "Edit upstream rather than this file. -->\n\n",
    body,
    "\n<!-- END nlmixr2llm -->\n"
  )

  if (file.exists(dst)) {
    if (mode == "error") {
      stop(sprintf("File already exists: %s", dst))
    } else if (mode == "append") {
      prev <- read_file(dst)
      body <- paste0(prev, "\n\n", body)
    }
  }

  writeLines(body, dst, useBytes = TRUE)

  n_bytes <- file.info(dst)$size
  if (isTRUE(n_bytes > 32 * 1024)) {
    warning(sprintf(
      paste0(
        "AGENTS.md is %.1f KiB, exceeding Codex's default 32 KiB cap. ",
        "Subset with `packages = ...` or `include = ...`, ",
        "or raise `project_doc_max_bytes` in ~/.codex/config.toml."
      ),
      n_bytes / 1024
    ))
  }

  message(sprintf("Wrote %s (%.1f KiB).", dst, n_bytes / 1024))
  invisible(dst)
}

codex_path <- function(scope, path) {
  if (scope == "user") {
    home <- Sys.getenv("CODEX_HOME", unset = NA)
    root <- if (!is.na(home) && nzchar(home)) {
      home
    } else {
      file.path(nlmixr2llm_home(), ".codex")
    }
    file.path(root, "AGENTS.md")
  } else {
    file.path(normalizePath(path, mustWork = FALSE), "AGENTS.md")
  }
}
