#' Install agents and skills for Positron Assistant
#'
#' Positron Assistant auto-discovers project-scoped instruction files in the
#' workspace root (per
#' `https://positron.posit.co/assistant-chat-instructions.html`). Two styles
#' are supported:
#'
#' * `style = "agents_md"` (default) -- writes a single `agents.md` at the
#'   workspace root. This is the file Positron looks for first, and it is also
#'   the shared `AGENTS.md` convention used by Codex, Cursor, Aider, Zed, and
#'   others, so this option gives broad coverage with one file.
#' * `style = "instructions"` -- writes one `<package>.instructions.md` per
#'   selected package (skill content) plus a single
#'   `nlmixr2verse.instructions.md` (the combined ecosystem agent) into
#'   `.github/instructions/`, each with `applyTo: "**/*.R"` so Positron
#'   Assistant attaches the content when editing R files.
#'
#' Positron does not document a user-level (cross-workspace) instructions
#' location. To get user-wide coverage, set up a per-project hook (for
#' example, in a project template) that calls `install_positron()`.
#'
#' @note On case-insensitive filesystems (macOS, Windows) the `agents.md` file
#'   written by `style = "agents_md"` and Codex's `AGENTS.md` (see
#'   [install_codex()] with `scope = "project"`) are the **same file**, so
#'   installing both into one project means the second call overwrites the
#'   first. With default arguments the instruction content is identical, so this
#'   is harmless; if you pass different `packages`/`include` to each, only the
#'   last call's selection survives. The `style = "instructions"` files
#'   (`.github/instructions/*.instructions.md`) do not collide.
#'
#' @param workspace Workspace (project) root. Defaults to the current working
#'   directory.
#' @param style One of `"agents_md"` (default) or `"instructions"`.
#' @param packages Character vector of nlmixr2-universe packages to include.
#'   Defaults to all available packages.
#' @param overwrite If `TRUE`, replace existing files. If `FALSE` (default),
#'   existing files are kept and a message is shown.
#' @param prune If `TRUE` (default), `style = "instructions"` removes
#'   previously installed `*.instructions.md` files that the current package
#'   version no longer ships, tracked via a manifest
#'   (`.github/instructions/.nlmixr2llm-manifest`). Only files nlmixr2llm
#'   created are removed. Ignored by `style = "agents_md"`, which writes a single
#'   fixed-name file with nothing to orphan.
#' @param apply_to Glob used in each `*.instructions.md` frontmatter when
#'   `style = "instructions"`. Defaults to `"**/*.R"`.
#' @return Invisibly, a character vector of files written.
#' @export
#' @examples
#' \dontrun{
#' install_positron(workspace = ".", style = "agents_md")
#' install_positron(workspace = ".", style = "instructions",
#'                  packages = c("rxode2", "nlmixr2"))
#' }
install_positron <- function(workspace = ".",
                             style = c("agents_md", "instructions"),
                             packages = NULL,
                             overwrite = FALSE,
                             prune = TRUE,
                             apply_to = "**/*.R") {
  style <- match.arg(style)
  workspace <- normalizePath(workspace, mustWork = FALSE)

  if (style == "agents_md") {
    dst <- file.path(workspace, "agents.md")
    pkgs <- intersect(packages %||% list_packages(), list_packages())
    body <- paste0(
      stamp_comment(pkgs), "\n",
      "<!-- Generated by the nlmixr2llm R package. ",
      "Edit upstream rather than this file. -->\n\n",
      system_prompt(packages = pkgs), "\n"
    )
    st <- write_if_allowed(dst, body, overwrite)
    if (st == "written") {
      message(sprintf("Wrote %s.", dst))
      return(invisible(dst))
    }
    message(sprintf("No change to %s.%s",
                    dst, drift_note(if (st == "stale") 1L else 0L)))
    return(invisible(character()))
  }

  packages <- packages %||% list_packages()
  packages <- intersect(packages, list_packages())
  if (!length(packages)) {
    stop("No matching packages. Available: ",
         paste(list_packages(), collapse = ", "))
  }

  dst_dir <- file.path(workspace, ".github", "instructions")
  dir.create(dst_dir, recursive = TRUE, showWarnings = FALSE)

  written <- character()
  n_stale <- 0L

  # Combined ecosystem agent -- one file spanning all packages.
  for (a in list_agents()) {
    dst <- file.path(dst_dir, sprintf("%s.instructions.md", a))
    body <- positron_md(
      name        = a,
      description = "nlmixr2 ecosystem agent (all packages)",
      body_md     = strip_frontmatter(get_agent(a)),
      apply_to    = apply_to
    )
    st <- write_if_allowed(dst, body, overwrite)
    if (st == "written") written <- c(written, dst)
    else if (st == "stale") n_stale <- n_stale + 1L
  }

  # Per-package skills.
  for (p in packages) {
    if (!(p %in% list_skills())) next
    dst <- file.path(dst_dir, sprintf("%s.instructions.md", p))
    body <- positron_md(
      name        = p,
      description = sprintf("nlmixr2 ecosystem guidance for %s", p),
      body_md     = strip_frontmatter(get_skill(p)),
      apply_to    = apply_to
    )
    st <- write_if_allowed(dst, body, overwrite)
    if (st == "written") written <- c(written, dst)
    else if (st == "stale") n_stale <- n_stale + 1L
  }

  # Prune obsolete instruction files this package installed previously. The
  # files live flat in dst_dir, so relative paths are just basenames.
  universe <- sprintf("%s.instructions.md", c(list_agents(), list_skills()))
  removed <- sync_manifest(dst_dir, universe, basename(written), prune)

  message(sprintf(
    "Wrote %d instruction file(s)%s into %s.%s",
    length(written),
    if (length(removed)) sprintf(", pruned %d obsolete", length(removed)) else "",
    dst_dir,
    drift_note(n_stale)
  ))
  invisible(written)
}

# Write `body` to `dst` unless it exists and `overwrite` is FALSE. Returns
# "written"; "stale" (skipped, but differs from what we would write -- an update
# is available); or "current" (skipped, identical).
write_if_allowed <- function(dst, body, overwrite) {
  if (file.exists(dst) && !overwrite) {
    tmp <- tempfile()
    on.exit(unlink(tmp), add = TRUE)
    writeLines(body, tmp, useBytes = TRUE)
    if (files_differ(tmp, dst)) {
      message(sprintf("  out of date (overwrite = TRUE to refresh): %s", dst))
      return("stale")
    }
    message(sprintf("  up to date: %s", dst))
    return("current")
  }
  writeLines(body, dst, useBytes = TRUE)
  "written"
}

positron_md <- function(name, description, body_md, apply_to) {
  paste0(
    "---\n",
    sprintf("name: %s\n", name),
    sprintf("description: %s\n", description),
    sprintf("applyTo: \"%s\"\n", apply_to),
    "---\n\n",
    stamp_comment(name), "\n\n",
    body_md, "\n"
  )
}
